// bundle mediabunny -> write it out as src/mediabunny.js (one of the source
// modules the rollup build stitches into the userscript).

import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const modulePath = resolve(here, '../../src/mediabunny.js');
const bannerPath = resolve(here, '../../src/_banner.txt');
const version = JSON.parse(
  readFileSync(resolve(here, 'node_modules/mediabunny/package.json'), 'utf8'),
).version;

const START = '// ==[Mediabunny start:]==';
const END = '// ==[/Mediabunny end]==';

const out = await build({
  entryPoints: [resolve(here, 'entry.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  globalName: '__MB',
  target: 'es2020',
  legalComments: 'none',
  write: false,
});

// esbuild hands back `var __MB = (() => {...})();`. Strip the `var __MB =` and the
// trailing `;` so we're left with just the IIFE, which we assign to `Mediabunny`.
let code = out.outputFiles[0].text.trim();
const m = code.match(/^var __MB\s*=\s*/);
if (!m) throw new Error('esbuild output looks different than expected');
const expr = code.slice(m[0].length).replace(/;\s*$/, '');

// The whole module is generated. Keep the markers so an editor / grep can find
// the boundary, and so this script has something to diff against next run.
const mod = `// Mediabunny — used to remux clips to MP4. It's big, so we only load it the first
// time someone actually uses Clip or Instant Replay.
${START}
/*!
 * Mediabunny ${version} — MPL-2.0 — https://github.com/Vanilagy/mediabunny
 * Trimmed build, generated by tools/mediabunny/build.mjs. Don't edit by hand.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
let Mediabunny = null, __ytee_mediabunnyFailed = false;
export const __ytee_loadMediabunny = () => {
  if (Mediabunny) return Mediabunny;
  if (__ytee_mediabunnyFailed) return null;
  try {
    Mediabunny = ${expr};
  } catch (e) {
    console.error('YTEE: Mediabunny failed to initialize', e);
    __ytee_mediabunnyFailed = true;
    return null;
  }
  return Mediabunny;
};
${END}
`;

let prev = '';
try { prev = readFileSync(modulePath, 'utf8'); } catch { }
const changed = prev !== mod;
writeFileSync(modulePath, mod, 'utf8');

let bumped = null;
if (changed) {
  const banner = readFileSync(bannerPath, 'utf8').replace(
    /(\/\/ @version\s+)(\d+)\.(\d+)\.(\d+)/,
    (_, p, maj, min, pat) => { bumped = `${maj}.${min}.${+pat + 1}`; return `${p}${bumped}`; },
  );
  writeFileSync(bannerPath, banner, 'utf8');
}

const kb = (s) => Math.round(s.length / 1024) + ' KB';
console.log(`mediabunny ${version}, bundle ${kb(expr)}`);
if (changed) {
  console.log(bumped ? `bundle changed — version bumped to ${bumped}` : 'bundle changed');
  console.log('run the userscript build to regenerate the bundled .user.js');
} else {
  console.log('no change');
}
